import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav.jsx";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Health Care App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >   
      <div className="w-full">
        <Nav />
        <div className="max-w-[1400px] mx-auto">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
