
export const metadata = {
  title: "Health Care App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >   
      <div className="container w-full max-w-[1200px] mx-auto px-4]">
      
        {children}
        </div>
      </body>
    </html>
  );
}